spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=10000
server.servlet.context-path=/api/v1.0
brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${BREVO_FROM_EMAIL}
jwt.secret=${JWT_SECRET}
money.manager.frontend.url=http://localhost:5173
app.activation.url=https://money-manager-api-1-92tu.onrender.com
logging.level.org.springframework.security=DEBUG