spring.datasource.url=jdbc:postgresql://dpg-d8dbboojs32c73fda7q0-a.singapore-postgres.render.com/moneymanager_89ga
spring.datasource.username=moneymanager_89ga_user
spring.datasource.password=aSnjnUGJjAfvqrNZTh9TpaqBMtZI0A19
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect